### ISSUE TITLE
Support automatic resizing the height of a chart

### ISSUE THREAD

**Issue by mia-mifeng** [adobe/react-spectrum-charts#216]
### Provide a general summary of the feature here

Currently for all the charts, automatic resizing is supported for the chart's width (via `width="100%"), yet not for the chart's height. See the picture below where the chart can auto resize its width with the widget container, but not height:
![image](https://github.com/adobe/react-spectrum-charts/assets/4145281/e5dfc012-6984-4cfc-a493-c532b671f754)

### 🤔 Expected Behavior?

All the charts can auto resize its height with its container.

### 🔦 Context

This feature is needed for migrating the UDD charts to use RSC.
Analysis doc: https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=AEPLT&title=UDD+Charts+RSC+Migration+Analysis

### 🧢 Your Company/Team

Adobe/AEP Reporting Experience

**Comment by carrickjason** [comment]
@marshallpete I would like to work on this for our team.
