### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum-charts#22]
### Provide a general summary of the issue here

In the `Support`(https://github.com/adobe/react-spectrum-charts#support) section of the README, the link `official documentation` is broken.

### 🤔 Expected Behavior?

Link works or isn't there.

### 😯 Current Behavior

Navigates to invalid URL.

### 💁 Possible Solution

Remove link or link to the documentation.

### 🖥️ Steps to Reproduce

goto https://github.com/adobe/react-spectrum-charts#support
click on `link-to-your-documentation`
browser navigates to `https://link-to-your-documentation/` which is invalid

### Version

main

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

OSX

### 🧢 Your Company/Team

Adobe

**Comment by marshallpete** [comment]
Thanks for highlighting this @ktabors. I have updated the link to point to our wiki which we are continually updating.
