### ISSUE TITLE
Request for Annotations feature for horizontal Bar Graphs

### ISSUE THREAD

**Issue by arushi474** [adobe/react-spectrum-charts#230]
### Provide a general summary of the feature here

Annotations doesn't work for bar graph when orientation is horizontal.

### 🤔 Expected Behavior?

![image](https://github.com/adobe/react-spectrum-charts/assets/72013238/480baa90-7974-4c3a-899b-e6c19d115066)

### 💁 Possible Solution

You can enable/build the annotaions to work for horizontal bar graph.

### 🔦 Context

![image](https://github.com/adobe/react-spectrum-charts/assets/72013238/8dde92df-35ee-414e-9af2-90745758554f)
As you can see it is enabled for verical bar graphs, But the same doesn't work for horizontal bar graphs.
As show below,
![image](https://github.com/adobe/react-spectrum-charts/assets/72013238/e5213c68-c64b-424e-b4fc-710b7ff4ae7e)

### 💻 Examples

This is the required behaviour

![image](https://github.com/adobe/react-spectrum-charts/assets/72013238/e5029c31-65e8-4540-b71b-aa1d6c09cc05)

### 🧢 Your Company/Team

Adobe/Connect

**Comment by marshallpete** [comment]
If you increase the height of your bar chart, do the annotations show up? We have something where if the width/height of the bar gets too small, the annotation won't show. Not saying it isn't a bug, just trying to troubleshoot a bit.

**Comment by arushi474** [comment]
Hey @marshallpete can you mention the specific height/width at which the annotations are hiden? I did explored the same by putting some values for the height/width prop in chart but could not get it to show the annotations for horizontal bar graph.

**Comment by marshallpete** [comment]
@arushi474  Sorry for the delay, I created another bug with more details and how to fix. I’ll fix this one next week. 
https://github.com/adobe/react-spectrum-charts/issues/268

**Comment by marshallpete** [comment]
Thanks again for the thorough details. You’ll see in the other issue that the root cause is that we never properly setup annotations for horizontal bars. If the width of the bar is less than 48px, we hide the annotation. This should be updated so that with a horizontal bar, if the height of the bar is less than the height of the text, we hide the annotation.

**Comment by arushi474** [comment]
Hey @marshallpete by when can I expect this to be fixed?

**Comment by marshallpete** [comment]
I might have some time next week or it's open for contribution if you want to take a crack at it.

**Comment by arushi474** [comment]
Hi @marshallpete any update on this?

**Comment by arushi474** [comment]
@marshallpete any update on this?
