### ISSUE TITLE
Donut chart support

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/react-spectrum-charts#28]
# Feature Request

Donut chart is available and fully featured. [Spectrum donut design guidelines](https://spectrum.adobe.com/page/donut-chart/)

<img width="344" alt="image" src="https://github.com/adobe/react-spectrum-charts/assets/40001449/7668b8e4-2510-4b3a-9888-32b5b93eed57">

# Donut Anatomy

https://spectrum.adobe.com/page/donut-chart/#Boolean
<img width="559" alt="image" src="https://github.com/adobe/react-spectrum-charts/assets/40001449/f7d177d5-b484-45a4-8014-e74c079e87e6">

# API
Should add the `Donut` component with the following props API.

```
export interface DonutProps extends Omit<MarkProps, 'color'> {
	/** donut segment color or key in the data that is used as the color facet */
	color?: ColorFacet;

	/** line type of the segment border or a key in the data that is used as the line type facet */
	lineType?: LineTypeFacet;

	/** line width of the segment border */
	lineWidth?: LineWidth;

	/** text label for the metric total */
	metricLabel?: string;
}

```

Potential future props
```
	/** start angle of the donut in radians (0 is top dead center) */
	startAngle?: number;

	/** ration of the donut inner radius / donut outer radius. 0 is a pie chart. 0.85 is the default. */
	donutHoleRatio?: number;

	/**
	 * sets whether donut chart should have a hole or not (name is a joke but I can't think of a better name at the moment)
	 * would only support donutHoleRatio or isBostonCream, not both
	 */
	isBostonCream?: boolean;
```

# Expected Behavior

- Donut should be centered in the chart area
- Hovering an arc should support a tooltip
- Hovering over an arc should lower the opacity of all other arcs (if tooltip exists)
- Selecting an arc should add a blue selection ring around that arc
- Selecting an arc should display a popover
- Metric total should be displayed in the center of the donut
- Metric label should be displayed under the metric total
  - If the metric label is undefined, then don't display it but update the metric total to be centered in the donut
- Should support a toggleable legend, allowing users to hide and show the various series in the chart
  - Hiding a series should remove it from the chart and the chart should redraw the arcs so that the visible series still add up to a full ring

## Open Questions

- Should the label title and label value shown in the mocks be added using props on the `Donut` or should they be added by adding an axis to the donut?
- Popover placement
  - Should the popover be centered above the arc like is currently done for all other chart types or is there a better placement for arcs
- Need to figure out how to size the metric total and metric label so that they are responsive and fill the available space without overlapping the donut

# Implementation

Start by identifying how to build out the vega spec for a spectrum donut chart (I'll attach a good starting point in the comments below).

Once the spec is in a good place and you are ready to implement, do the following:

Note: For each of the following, follow the patterns established by `Bar`, `Line` and `Area`.

1. Add a `Donut` component to the `components/` folder.
2. Create a `Donut.stories` file in the `stories/` folder and add stories demonstrating each prop.
3. Setup the `donut/donutSpecBuilder.ts` in the `specBuilder/` folder.
4. Follow all the coding patterns that have been established.
5. Add the `addDonut` function to the reduce in `chartSpecBuilder.ts`.

# Future Work

### Boolean Donut

https://spectrum.adobe.com/page/donut-chart/#Boolean

Need to decide how we want to support a boolean variant. Should it be a separte component or should it be a variant of the `Donut` component?
  
<img width="345" alt="image" src="https://github.com/adobe/react-spectrum-charts/assets/40001449/3adde703-4b49-411c-92d9-d376837f89a0">

**Comment by marshallpete** [comment]
Here is a good starting point for the spec. This does not use the spectrum text or color theming but you get those for free with the specBuilder.

Try copying and pasting the full spec into the [vega editor](https://vega.github.io/editor) and make sure that the type of spec is set to `Vega` in the top left.

<img width="153" alt="image" src="https://github.com/adobe/react-spectrum-charts/assets/40001449/c3ce83bf-aa87-4ba8-8abc-3dc1fbf05bb6">



<img width="319" alt="image" src="https://github.com/adobe/react-spectrum-charts/assets/40001449/15e6cbee-fa3c-41b7-96ab-8f3c48017c5e">


spec:
```
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A basic donut chart example.",
  "width": 300,
  "height": 300,
  "autosize": "none",
  "signals": [{"name": "donutRadius", "update": "min(width, height) / 2"}],
  "data": [
    {
      "name": "table",
      "values": [
        {"id": 1, "field": 4},
        {"id": 2, "field": 6},
        {"id": 3, "field": 10},
        {"id": 4, "field": 3},
        {"id": 5, "field": 7},
        {"id": 6, "field": 8}
      ],
      "transform": [
        {
          "type": "pie",
          "field": "field",
          "startAngle": 0,
          "endAngle": {"signal": "2 * PI"}
        }
      ]
    },
    {
      "name": "donut0_agregate",
      "source": "table",
      "transform": [
        {
          "type": "aggregate",
          "fields": ["field"],
          "ops": ["sum"],
          "as": ["sum"]
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table", "field": "id"},
      "range": {"scheme": "category20"}
    }
  ],
  "marks": [
    {
      "type": "arc",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "fill": {"scale": "color", "field": "id"},
          "x": {"signal": "width / 2"},
          "y": {"signal": "height / 2"}
        },
        "update": {
          "startAngle": {"field": "startAngle"},
          "endAngle": {"field": "endAngle"},
          "padAngle": {"value": 0.01},
          "innerRadius": {"signal": "0.85* donutRadius"},
          "outerRadius": {"signal": "min(width, height) / 2"}
        }
      }
    },
    {
      "type": "group",
      "name": "donut0_metricLabel",
      "marks": [
        {
          "type": "text",
          "from": {"data": "donut0_agregate"},
          "encode": {
            "enter": {
              "x": {"signal": "width / 2"},
              "y": {"signal": "height / 2"},
              "text": {"signal": "upper(replace(format(datum.sum, '.3~s'), 'G', 'B'))"},
              "fontSize": {"value": 72},
              "align": {"value": "center"}
            }
          }
        },
        {
          "type": "text",
          "from": {"data": "donut0_agregate"},
          "encode": {
            "enter": {
              "x": {"signal": "width / 2"},
              "y": {"signal": "height / 2", "offset": 24},
              "text": {"value": "Visitors"},
              "fontSize": {"value": 24},
              "align": {"value": "center"},
              "baseline": {"value": "top"},
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by marshallpete** [comment]
The above spec does not support hover states, select states, highlight from legend, or hide/show from the legend (isToggleable). Hence why it is a "good starting point".

**Comment by alangwilson** [comment]
It would be nice to split label value into two things: percent and count. Users can configure the chart to have one, both, or neither. The same should apply to these values in a legend or the hover inspect/tooltip when we get to those.
