### ISSUE TITLE
Donut (alpha) size less than 100

### ISSUE THREAD

**Issue by natvilla** [adobe/react-spectrum-charts#288]
### Provide a general summary of the issue here

Creating a Donut with size less than 100 always creates an svg with size equal to 100. It doesn't seem possible to create a size smaller than 100 using width/height. It's still possible to create a smaller size using padding.  

### 🤔 Expected Behavior?

The svg should be the same inputted width/height as the Chart props.

### 😯 Current Behavior

Actual svg width/height is always 100 when Chart props are less than 100.
<img width="1613" alt="Screen Shot 2024-05-07 at 12 02 41 PM" src="https://github.com/adobe/react-spectrum-charts/assets/2700336/63391d4d-0567-4655-baa7-a63b3bac2165">

### 🖥️ Steps to Reproduce

```      
<Chart
    colorScheme={colorScheme}
    colors={[fillColor, REMAINDER_COLOR]}
    data={data}
    description={description}
    height={65}
    locale={locale}
    width={65}
>
    <RSCDonut {...donutProps} />
</Chart>
```

### Version

1.6.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Monterey

### 🧢 Your Company/Team

Adobe Agora

**Comment by marshallpete** [comment]
With the recent dynamic chart height changes. It's possible that a minHeight of 100 was added. We need to update that. min height and min width should only be used when width/height are relative values (percentages).
