### ISSUE TITLE
Non-obvious props should have documentation

### ISSUE THREAD

**Issue by ToyWalrus** [adobe/react-spectrum-charts#32]
### 🙋 Documentation Request

I noticed that many of the props in the `types/Chart.ts` file, while they may have an inline comment explaining them, they don't actually have a doc comment. I think these should be changed to doc comments so that the users of the library can see what each prop does through their IDE's intellisense feature, rather than needing to comb through the source code to see how it works/what it does.

For example, the `LineProps` type currently has only one doc comment, though all of the other props _do have comments_ explaining them. https://github.com/adobe/react-spectrum-charts/blob/main/src/types/Chart.ts#L247

### 🧢 Your Company/Team

Adobe/Analytics

**Comment by marshallpete** [comment]
All props are documented and have explanations in the [API docs](https://github.com/adobe/react-spectrum-charts/wiki/Chart-API)

**Comment by marshallpete** [comment]
Will add jsdocs to all props

**Comment by marshallpete** [comment]
Completed with above PR
