### ISSUE TITLE
yarn storybook fails on Windows

### ISSUE THREAD

**Issue by jacob-hart** [adobe/react-spectrum-charts#85]
### Provide a general summary of the issue here

`yarn storybook` fails to run on Windows.  This is because the `export` command is not available.  Instead, a Windows developer must manually change `export` to `setx`.

### 🤔 Expected Behavior?

`yarn storybook` works

### 😯 Current Behavior

`export` is not available on Windows

### 💁 Possible Solution

I want to change `yarn storybook` to use `cross-env`, like other commands in `package.json`.

### 🖥️ Steps to Reproduce

1. Use Windows
2. Clone this repo and install dependencies.
3. Attempt to run `yarn storybook`.

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by jacob-hart** [comment]
PR here https://github.com/adobe/react-spectrum-charts/pull/86

**Comment by marshallpete** [comment]
Awesome! Thanks for the fix!
